apiVersion: v1
kind: Secret
metadata:
  name: oh-arma-test-config
type: Opaque
stringData:
  armadietto.conf.json: |
    {
      "allow_signup": false,
      "storage_path": "/usr/share/armadietto",
      "terms_of_service_url": "https://overhide.io/lib/tos.html",
      "cache_views": true,
      "http": {
        "host": "0.0.0.0",
        "port": 8000
      },
      "https": {
        "enable": false,
        "force": false,
        "port": 4443,
        "cert": "/etc/letsencrypt/live/example.com/cert.pem",
        "key": "/etc/letsencrypt/live/example.com/privkey.pem"
      },
      "logging": {
        "log_dir": "logs",
        "stdout": ["info"],
        "log_files": ["error"]
      },
      "basePath": "",
      "extensions": {
        "storage_allowance": {
          "enabled": true,
          "max_bytes": 10485760,
          "salt": "..."
        },
        "liveness_probe": {
          "enabled": true,
          "user": "sysop",
          "file_path": "/status.txt",
          "file_size_bytes": 64,
          "url_path": "status.txt"
        },
        "rate_limiter": {
          "enabled": true,
          "requests_per_window": 20,
          "limiting_window_seconds": 10,
          "redis_url": "redis://redis:6379"
        },
        "pay2myapp": {
          "enabled": true,
          "is_test": true,
          "api_key": "...",
          "price_dollars": 1.99,
          "within_days": 3,
          "address": "...",
          "internal_token": "...",
          "retention_policy_text": "<em>Your data has no retantion guarantees on this <b>test server</b>.</em>",
          "salt": "...",
          "allows": "allow-popups",
          "allowed_script_src": "'self' *.overhide.io *.stripe.com 'nonce-FIw2-XPuBuqHUejwlDVQJA' 'nonce-C8oQ_7qi6IQ9eQdjd1_PMg'",
          "allowed_connect_src": "*.overhide.io *.stripe.com *.5apps.com",
          "allowed_style_src": "'self' 'unsafe-inline'",
          "allowed_default_src": "'self' *.stripe.com",
          "allowed_frame_src": "'self' *.overhide.io overhide.github.io overhide.b2clogin.com *.stripe.com",
          "allowed_frame_ancestors": "'self'"
        }    
      }
    }
